/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akass
 */
public class Active_account extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    /**
     * Creates new form Active_account
     */
    public Active_account() {
        initComponents();
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM account WHERE Status='Active'";
        dtm=(DefaultTableModel)Account_t.getModel();
        dtm.setRowCount(0);
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            int i=1;
            while(rs.next()){
                dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getDouble(4),rs.getDouble(5)});
                      
            }
        }catch(Exception e){
                    System.out.println("err");
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Account_t = new javax.swing.JTable();
        Del_member = new javax.swing.JLabel();
        Search_n = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        ref = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 700));

        Account_t.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Account_t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No", "Account ID", "Name", "Account", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Account_t);
        if (Account_t.getColumnModel().getColumnCount() > 0) {
            Account_t.getColumnModel().getColumn(0).setMinWidth(50);
            Account_t.getColumnModel().getColumn(0).setPreferredWidth(50);
            Account_t.getColumnModel().getColumn(0).setMaxWidth(50);
            Account_t.getColumnModel().getColumn(1).setMinWidth(80);
            Account_t.getColumnModel().getColumn(1).setPreferredWidth(80);
            Account_t.getColumnModel().getColumn(1).setMaxWidth(80);
            Account_t.getColumnModel().getColumn(3).setMinWidth(150);
            Account_t.getColumnModel().getColumn(3).setPreferredWidth(150);
            Account_t.getColumnModel().getColumn(3).setMaxWidth(150);
            Account_t.getColumnModel().getColumn(4).setMinWidth(150);
            Account_t.getColumnModel().getColumn(4).setPreferredWidth(150);
            Account_t.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        Del_member.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.PNG"))); // NOI18N
        Del_member.setText("Deactivate");
        Del_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Del_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Del_memberMouseExited(evt);
            }
        });

        Search_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_nActionPerformed(evt);
            }
        });

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        ref.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        ref.setText("Refresh");
        ref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refMouseExited(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 0, 0));
        Title.setText("Active Members");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(246, 246, 246)
                        .addComponent(Search_n)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Del_member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search_n, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(Search)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Title)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Del_member, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
            String name=Search_n.getText();
        String sql="SELECT * FROM account WHERE 1=1"; //this selects all the rows
               if(!"".equals(name)){
            sql+=" AND Name LIKE '"+name+"%'"; //if blank will not return anything
            //displaying filtered names
        con=DBconnection.makeconnection();
            dtm=(DefaultTableModel)Account_t.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                    int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getDouble(4),rs.getDouble(5)});
                
                    }
                }
                catch(Exception e){
                    System.out.println("Query not executed");
                }
      
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void Del_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseClicked
            int noofselectedrows= Account_t.getSelectedRowCount();
            
            if(noofselectedrows>0){
                int rowno=Account_t.getSelectedRow();
                
               // System.out.println(rowno); // kati no ko row select bhayo bhanera dekhauchha
                Object aid=Account_t.getValueAt(rowno, 1);//this line gies the id of the table like 1,2,3 
                int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to Deactivate this Account?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                //System.out.println(confirmdelete);
             //   System.out.println(cid);
                
                String sql="UPDATE account SET status='Deactive' WHERE AID='"+aid+"'";
                if(confirmdelete==0){
                    dtm.removeRow(rowno);//this removable is remoaved by the model
                    
                    try{
                        //now this step is to delete prmanently in database aswell 
                       Statement st=con.createStatement();
                       st.executeUpdate(sql);
                       
                       JOptionPane.showMessageDialog(this,"Account Deactivated!!!", "Alert",JOptionPane.PLAIN_MESSAGE);
            
                    }catch(Exception e){
                        System.out.println("query not executed");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this,"Please select a record", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseClicked

    private void Search_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_nActionPerformed

    private void refMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refMouseClicked
        HomeFrame.changePanel(new Active_account());        // TODO add your handling code here:
    }//GEN-LAST:event_refMouseClicked

    private void Del_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseEntered
        Del_member.setOpaque(true);
        Del_member.setBackground(Color.pink);        // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseEntered

    private void Del_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseExited
        Del_member.setBackground(Color.white);
        Del_member.setOpaque(false);             // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseExited

    private void refMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refMouseEntered
        ref.setOpaque(true);
        ref.setBackground(Color.pink);   // TODO add your handling code here:
    }//GEN-LAST:event_refMouseEntered

    private void refMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refMouseExited
        ref.setBackground(Color.white);
        ref.setOpaque(false);  // TODO add your handling code here:
    }//GEN-LAST:event_refMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Account_t;
    private javax.swing.JLabel Del_member;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Search_n;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ref;
    // End of variables declaration//GEN-END:variables
}
