/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;

import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Akass
 */
public class Add_Member extends javax.swing.JPanel {
    String profilepic=null;
    
    /**
     * Creates new form Add_Member
     */
    public Add_Member() {
        initComponents();
       
        
    
  
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Cp = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Basic_info = new javax.swing.JPanel();
        F_name = new javax.swing.JLabel();
        F_name_n = new javax.swing.JTextField();
        F_name_err = new javax.swing.JLabel();
        L_name = new javax.swing.JLabel();
        L_name_n = new javax.swing.JTextField();
        L_name_err = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Citizenship = new javax.swing.JLabel();
        Citizenship_n = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        ID_n = new javax.swing.JTextField();
        Membership_type = new javax.swing.JLabel();
        Membership_n = new javax.swing.JComboBox();
        Dp = new javax.swing.JLabel();
        Upload = new javax.swing.JButton();
        Ctzn_no = new javax.swing.JLabel();
        Ctzn_n = new javax.swing.JTextField();
        Contact_info = new javax.swing.JPanel();
        Address = new javax.swing.JLabel();
        Permanent = new javax.swing.JLabel();
        Permanent_n = new javax.swing.JTextField();
        Permanent_n_err = new javax.swing.JLabel();
        Temporary = new javax.swing.JLabel();
        Temporary_n = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home_n = new javax.swing.JTextField();
        Mobile = new javax.swing.JLabel();
        Mobile_n = new javax.swing.JTextField();
        Mobile_n_err = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Email_n = new javax.swing.JTextField();
        Other_info = new javax.swing.JPanel();
        Father_n = new javax.swing.JTextField();
        Father = new javax.swing.JLabel();
        Gfather = new javax.swing.JLabel();
        Gfather_n = new javax.swing.JTextField();
        Mother = new javax.swing.JLabel();
        Mother_n = new javax.swing.JTextField();
        ED = new javax.swing.JLabel();
        Entry_n = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Counter = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 730));

        Cp.setBackground(new java.awt.Color(255, 255, 255));
        Cp.setPreferredSize(new java.awt.Dimension(901, 710));
        Cp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CpMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 0, 0));
        Title.setText("Fill the details below");

        Basic_info.setBackground(new java.awt.Color(204, 204, 255));
        Basic_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Basic_info.setForeground(new java.awt.Color(153, 153, 255));
        Basic_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Basic_infoMouseClicked(evt);
            }
        });

        F_name.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        F_name.setText("First Name");

        F_name_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_name_nActionPerformed(evt);
            }
        });
        F_name_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                F_name_nKeyTyped(evt);
            }
        });

        F_name_err.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        F_name_err.setForeground(new java.awt.Color(255, 0, 0));

        L_name.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        L_name.setText("Last Name");

        L_name_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_name_nActionPerformed(evt);
            }
        });
        L_name_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                L_name_nKeyTyped(evt);
            }
        });

        L_name_err.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        L_name_err.setForeground(new java.awt.Color(255, 0, 0));

        Gender.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Gender.setText("Gender");

        Male.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(Male);
        Male.setText("Male");
        Male.setActionCommand("M");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(Female);
        Female.setText("Female");
        Female.setActionCommand("F");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Citizenship.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Citizenship.setText("Citizenship");

        Citizenship_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citizenship_nActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ID.setText("ID");

        ID_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_nActionPerformed(evt);
            }
        });

        Membership_type.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Membership_type.setText("Membership Type");

        Membership_n.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "General", "Founder", "Executive" }));
        Membership_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Membership_nActionPerformed(evt);
            }
        });

        Dp.setBackground(new java.awt.Color(255, 255, 255));
        Dp.setForeground(new java.awt.Color(255, 255, 255));
        Dp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man.jpg"))); // NOI18N
        Dp.setPreferredSize(new java.awt.Dimension(200, 120));

        Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginpng.png"))); // NOI18N
        Upload.setText("Upload");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        Ctzn_no.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Ctzn_no.setText("Ctzn no.");

        Ctzn_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ctzn_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Basic_infoLayout = new javax.swing.GroupLayout(Basic_info);
        Basic_info.setLayout(Basic_infoLayout);
        Basic_infoLayout.setHorizontalGroup(
            Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basic_infoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Dp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basic_infoLayout.createSequentialGroup()
                                .addComponent(ID)
                                .addGap(26, 26, 26)
                                .addComponent(ID_n, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Basic_infoLayout.createSequentialGroup()
                                    .addGap(378, 378, 378)
                                    .addComponent(Ctzn_no)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Ctzn_n, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Basic_infoLayout.createSequentialGroup()
                                    .addGap(363, 363, 363)
                                    .addComponent(L_name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L_name_n, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(F_name_err, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_name_n, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Basic_infoLayout.createSequentialGroup()
                                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Membership_type, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(F_name)
                                        .addComponent(Citizenship))
                                    .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39)
                                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Citizenship_n, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Membership_n, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Basic_infoLayout.createSequentialGroup()
                                        .addComponent(Male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Female)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_name_err, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Basic_infoLayout.setVerticalGroup(
            Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basic_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F_name)
                            .addComponent(L_name)
                            .addComponent(L_name_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_name_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_name_err, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F_name_err, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Citizenship)
                                .addComponent(Citizenship_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Ctzn_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ctzn_no)))
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Basic_infoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ID_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basic_infoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Membership_type)
                                    .addComponent(Membership_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Gender)
                                .addComponent(Male))
                            .addComponent(Female))
                        .addContainerGap())
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addComponent(Dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upload)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        Contact_info.setBackground(new java.awt.Color(204, 204, 255));
        Contact_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Contact_info.setForeground(new java.awt.Color(153, 153, 255));

        Address.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Address.setText("Address");

        Permanent.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Permanent.setText("Permanent");

        Permanent_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Permanent_nActionPerformed(evt);
            }
        });
        Permanent_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Permanent_nKeyTyped(evt);
            }
        });

        Permanent_n_err.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Permanent_n_err.setForeground(new java.awt.Color(204, 0, 0));

        Temporary.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Temporary.setText("Temporary");

        Temporary_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Temporary_nActionPerformed(evt);
            }
        });

        Contact.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Contact.setText("Contact");

        Home.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Home.setText("Home number");

        Home_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_nActionPerformed(evt);
            }
        });

        Mobile.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Mobile.setText("Mobile number");

        Mobile_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobile_nActionPerformed(evt);
            }
        });
        Mobile_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mobile_nKeyTyped(evt);
            }
        });

        Mobile_n_err.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Mobile_n_err.setForeground(new java.awt.Color(204, 0, 0));

        Email.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Email.setText("Email ID");

        Email_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Contact_infoLayout = new javax.swing.GroupLayout(Contact_info);
        Contact_info.setLayout(Contact_infoLayout);
        Contact_infoLayout.setHorizontalGroup(
            Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_infoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address)
                    .addComponent(Permanent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Temporary, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Permanent_n)
                        .addComponent(Temporary_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Permanent_n_err, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addComponent(Email)
                        .addGap(47, 47, 47)
                        .addComponent(Email_n, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Contact_infoLayout.createSequentialGroup()
                            .addComponent(Contact)
                            .addGap(45, 45, 45)
                            .addComponent(Mobile_n_err, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contact_infoLayout.createSequentialGroup()
                            .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Contact_infoLayout.createSequentialGroup()
                                    .addComponent(Mobile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Mobile_n, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Contact_infoLayout.createSequentialGroup()
                                    .addComponent(Home)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Home_n, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(23, 23, 23))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Contact_infoLayout.setVerticalGroup(
            Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_infoLayout.createSequentialGroup()
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mobile_n_err, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Permanent_n_err, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Address)
                                    .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mobile_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mobile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home)
                            .addComponent(Home_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email)
                            .addComponent(Email_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Permanent)
                            .addComponent(Permanent_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Temporary)
                            .addComponent(Temporary_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Other_info.setBackground(new java.awt.Color(204, 204, 255));
        Other_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Other_info.setForeground(new java.awt.Color(153, 153, 255));

        Father_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Father_nActionPerformed(evt);
            }
        });

        Father.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Father.setText("Father's name");

        Gfather.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Gfather.setText("Grandfather's name");

        Gfather_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gfather_nActionPerformed(evt);
            }
        });

        Mother.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Mother.setText("Mother's name");

        Mother_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mother_nActionPerformed(evt);
            }
        });

        ED.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ED.setText("Entry Diposit");

        Entry_n.setText("0.0");
        Entry_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entry_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Other_infoLayout = new javax.swing.GroupLayout(Other_info);
        Other_info.setLayout(Other_infoLayout);
        Other_infoLayout.setHorizontalGroup(
            Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Other_infoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Other_infoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Father))
                    .addComponent(Gfather)
                    .addComponent(Mother))
                .addGap(10, 10, 10)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Other_infoLayout.createSequentialGroup()
                        .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gfather_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Other_infoLayout.createSequentialGroup()
                                .addComponent(Father_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(ED)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Other_infoLayout.createSequentialGroup()
                        .addComponent(Mother_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Entry_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
        );
        Other_infoLayout.setVerticalGroup(
            Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Other_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ED)
                    .addComponent(Father_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Father))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mother)
                        .addComponent(Mother_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Entry_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gfather)
                    .addComponent(Gfather_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        Cancel.setText("Cancel");
        buttonGroup2.add(Cancel);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Grant.png"))); // NOI18N
        Submit.setText("Submit");
        buttonGroup2.add(Submit);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Counter.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        Counter.setForeground(new java.awt.Color(204, 0, 0));
        Counter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CounterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CpLayout = new javax.swing.GroupLayout(Cp);
        Cp.setLayout(CpLayout);
        CpLayout.setHorizontalGroup(
            CpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Basic_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contact_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Other_info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CpLayout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(138, 138, 138)
                        .addComponent(Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Submit)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel)))
                .addContainerGap())
        );
        CpLayout.setVerticalGroup(
            CpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Basic_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Contact_info, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Other_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(Cp, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cp, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void Permanent_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Permanent_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Permanent_nActionPerformed

    private void Mobile_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobile_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_nActionPerformed

    private void Home_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_nActionPerformed

    private void Temporary_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Temporary_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Temporary_nActionPerformed

    private void Email_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_nActionPerformed

    private void ID_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_nActionPerformed

    private void Father_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Father_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Father_nActionPerformed

    private void Gfather_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gfather_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gfather_nActionPerformed

    private void Mother_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mother_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mother_nActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
         buttonGroup1.clearSelection();
        //Year.setSelectionIndex();
        F_name_n.setText("");
       
        L_name_n.setText("");
        Mobile_n.setText("");
        Home_n.setText("");
        Email_n.setText("");
        ID_n.setText("");
        Permanent_n.setText("");
        Entry_n.setText("");
        Temporary_n.setText("");
        Father_n.setText("");
        Mother_n.setText("");
        Gfather_n.setText("");
        Ctzn_n.setText("");
        Citizenship_n.setText("");
        Membership_n.setSelectedIndex(0);
        
        HomeFrame.changePanel(new Display_members());
        //Id_no.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void L_name_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_name_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_name_nActionPerformed

    private void Ctzn_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ctzn_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ctzn_nActionPerformed

    private void Citizenship_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citizenship_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citizenship_nActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
        String firstname=F_name_n.getText();
        if(Validate.checklength(firstname)==false){
           //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
            F_name_err.setText("First name cannot be empty!!!");
            F_name_n.requestFocus();
            return;
       }
        String lastname=L_name_n.getText();
        if(Validate.checklength(lastname)==false){
           // JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
            L_name_err.setText("First name cannot be empty!!!");
            L_name_n.requestFocus();
            return;
       }
        String Gender="";
        if(buttonGroup1.getSelection()==null){
            JOptionPane.showMessageDialog(this,"Please provide your gender","Alert",JOptionPane.PLAIN_MESSAGE);
            return;
        }else{
            Gender=buttonGroup1.getSelection().getActionCommand();
        }
        String permanent=Permanent_n.getText();
        if(Validate.checklength(permanent)==false){
           // JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
            Permanent_n_err.setText("Permanent address cannot be empty!!!");
            Permanent_n.requestFocus();
            return;
       }
        String mobile=Mobile_n.getText();
        if(Validate.checklength(mobile)==false){
           // JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
            Mobile_n_err.setText("Mobile no. cannot be empty!!!");
            Mobile_n.requestFocus();
            return;
       }
        
        String name=F_name_n.getText()+" "+L_name_n.getText();
        String gender=buttonGroup1.getSelection().getActionCommand();
        //String dob=Year.getSelectedItem().toString()+"-"+Month.getSelectedItem().toString()+"-"+Day.getSelectedItem().toString();
        String citizenship=Citizenship_n.getText();
        String ctzn=Ctzn_n.getText();
        String membership=Membership_n.getSelectedItem().toString();
        String cid=ID_n.getText();
        String permanent_a=Permanent_n.getText();
        String temporary_a=Temporary_n.getText();
           
        String mobile_n=Mobile_n.getText();
        String home_n=Home_n.getText();
        String email=Email_n.getText();
        String father=Father_n.getText();
        String mother=Mother_n.getText();
        String gfather=Gfather_n.getText();
        String account=Entry_n.getText();
        
            System.out.println(name+gender+citizenship+ctzn+membership+cid+permanent_a+temporary_a+mobile_n+home_n+email+father+mother+gfather);
        try {
                Class.forName("com.mysql.jdbc.Driver");
                //library ma vako kun chai driver load garney vanera java lae vaneko
            }
            catch (Exception t){
                System.out.println("DB NOT CONNECTED");
            }
                Connection con = null;
                Statement st = null;
                String url = "jdbc:mysql://localhost:3306/HMC";
                String user = "root";
                String password = "";
        
        try {
            con =  DriverManager.getConnection(url, user, password);
            st = con.createStatement();

        }catch(Exception ea){
            System.out.println("statement error");
        }
        String Image;
         if(this.profilepic==null){
             Image="E:/default.jpg";
             System.out.println("default pic");
         }else{
            Image="E:/hm.jpg";
         }
        String sql="INSERT INTO members(Aid,Name,Gender,Citizenship,Ctzn_no,Membership_type,Permanent_address,Temporary_address,Mobile_no,Home_no,Email,Father,Mother,Grandfather,Photo) VALUES('"+cid+"','"+name+"','"+gender+"','"+citizenship+"','"+ctzn+"','"+membership+"','"+permanent_a+"','"+temporary_a+"','"+mobile_n+"','"+home_n+"','"+email+"','"+father+"','"+mother+"','"+gfather+"',LOAD_FILE('"+Image+"'))";//INSERT INTO new(Image) VALUES(LOAD_FILE('D:/Image/a.jpg'));
        String sql2="INSERT INTO account(Aid,Name,Account,Share,Status,bonus,invested) VALUES('"+cid+"','"+name+"','"+account+"',0,'Active',0,0)";
        String sql3="INSERT INTO saving_record (Aid, Name, Date1, Baishak, Date2, Jestha, Date3, Ashad, Date4, Shrawan, Date5, Bhadra, Date6, Aswin, Date7, Kartik, Date8, Mangsir, Date9, Poush, Date10, Magh, Date11, Falgun, Date12, Chaitra) VALUES ( '"+cid+"', '"+name+"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')";
        
        try{
            st.execute(sql);
            st.execute(sql2);
            st.execute(sql3);
            
            int newrecord=JOptionPane.showConfirmDialog(this, "Member Successfully Added!!! Do you want to add more??", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
            if(newrecord==0){
                HomeFrame.changePanel(new Add_Member());
               }else{
                    HomeFrame.changePanel(new Display_members());
               } 
            
        }catch(Exception e){
            System.out.println(sql3);
            System.out.println(sql2);
            System.out.println(sql);
            JOptionPane.showMessageDialog(this,"Member ID already exixts, Provide new Membership ID!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                    
        }
        /*        
        buttonGroup1.clearSelection();
        F_name_n.setText("");
       
        L_name_n.setText("");
        Mobile_n.setText("");
        Home_n.setText("");
        Email_n.setText("");
        ID_n.setText("");
        Permanent_n.setText("");
        Entry_n.setText("");
        Temporary_n.setText("");
        Father_n.setText("");
        Mother_n.setText("");
        Gfather_n.setText("");
        Ctzn_n.setText("");
        Citizenship_n.setText("");
        Membership_n.setSelectedIndex(0);
        Counter.setText("Member Added Successfully");*/


// TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void F_name_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_F_name_nKeyTyped
        F_name_err.setText("");
        Counter.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_F_name_nKeyTyped

    private void L_name_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L_name_nKeyTyped
    L_name_err.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_L_name_nKeyTyped

    private void Permanent_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Permanent_nKeyTyped
    Permanent_n_err.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Permanent_nKeyTyped

    private void Mobile_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mobile_nKeyTyped
    Mobile_n_err.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_nKeyTyped

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed

        
    //Upload picture in account form  
           
          JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              Dp.setIcon(ResizeImage(path));
              profilepic=path;
              System.out.println(path);
              int i=1;
              try{
                    BufferedImage image = ImageIO.read(selectedFile);
                    System.out.println(selectedFile);
                    ImageIO.write(image,"jpg",new File("E:\\hm.jpg"));
                    i++;
              }catch(IOException f){
                  System.out.println("fail");
              }
          }
           //if the user click on save in Jfilechooser
          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
              return;
          }
            setLayout(null);
           // setDefaultCloseOperation(jPanel1.EXIT_ON_CLOSE);
            //setLocationRelativeTo(null);
            setSize(200,120);
            setVisible(true);
            
        
 
    }//GEN-LAST:event_UploadActionPerformed

    private void CounterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CounterMouseClicked
        Counter.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_CounterMouseClicked

    private void Basic_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Basic_infoMouseClicked
        Counter.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_Basic_infoMouseClicked

    private void CpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CpMouseClicked
    Counter.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_CpMouseClicked

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void F_name_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_name_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_name_nActionPerformed

    private void Membership_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Membership_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Membership_nActionPerformed

    private void Entry_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entry_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entry_nActionPerformed
    //Resizing the image
   public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        java.awt.Image img = MyImage.getImage();
        java.awt.Image newImg = img.getScaledInstance(Dp.getWidth(), Dp.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
   /* private static void save(BufferedImage image, String ext) {
        String fileName[];
        File file = new File(fileName + "." + ext);
        //BufferedImage image = toBufferedImage(file);
        try {
                ImageIO.write(image, ext, file);  // ignore returned boolean
        } catch(IOException e) {
                System.out.println("Write error for " + file.getPath() +": " + e.getMessage());
    }
 }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JPanel Basic_info;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Citizenship;
    private javax.swing.JTextField Citizenship_n;
    private javax.swing.JLabel Contact;
    private javax.swing.JPanel Contact_info;
    private javax.swing.JLabel Counter;
    private javax.swing.JPanel Cp;
    private javax.swing.JTextField Ctzn_n;
    private javax.swing.JLabel Ctzn_no;
    private javax.swing.JLabel Dp;
    private javax.swing.JLabel ED;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Email_n;
    private javax.swing.JTextField Entry_n;
    private javax.swing.JLabel F_name;
    private javax.swing.JLabel F_name_err;
    private javax.swing.JTextField F_name_n;
    private javax.swing.JLabel Father;
    private javax.swing.JTextField Father_n;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gfather;
    private javax.swing.JTextField Gfather_n;
    private javax.swing.JLabel Home;
    private javax.swing.JTextField Home_n;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField ID_n;
    private javax.swing.JLabel L_name;
    private javax.swing.JLabel L_name_err;
    private javax.swing.JTextField L_name_n;
    private javax.swing.JRadioButton Male;
    private javax.swing.JComboBox Membership_n;
    private javax.swing.JLabel Membership_type;
    private javax.swing.JLabel Mobile;
    private javax.swing.JTextField Mobile_n;
    private javax.swing.JLabel Mobile_n_err;
    private javax.swing.JLabel Mother;
    private javax.swing.JTextField Mother_n;
    private javax.swing.JPanel Other_info;
    private javax.swing.JLabel Permanent;
    private javax.swing.JTextField Permanent_n;
    private javax.swing.JLabel Permanent_n_err;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Temporary;
    private javax.swing.JTextField Temporary_n;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Upload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
