/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.awt.Color;
import java.awt.GridLayout;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Akass
 */
public class Admin_panel extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    static String[] ConnectOptionNames = { "Login", "Cancel" };
    static String   ConnectTitle = "User Log in";
  
       public Admin_panel() {
        initComponents();
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM security WHERE 1=1";
        
        dtm=(DefaultTableModel)A_table.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                     int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{rs.getInt(1),i++,rs.getString(2)});
                      
                    }                 
                }catch(Exception e){
                    System.out.println("Query not executed ");
                }
                
                 TableColumnModel tcm=A_table.getColumnModel();
                TableColumn tc=tcm.getColumn(0);
                tc.setPreferredWidth(0);
                tc.setMinWidth(0);
                tc.setMaxWidth(0);
    }
       
       
        public void reset()
    {
        System.out.println("success");
        
        con=DBconnection.makeconnection();
        int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to erase all the data permanently?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                //System.out.println(confirmdelete);
             //   System.out.println(cid);
                if(confirmdelete==0){
                   
                         try{
                                Statement st=con.createStatement();
                                st.execute("DELETE FROM members");
                                st.execute("DELETE FROM account");
                                st.execute("UPDATE capital SET Monthly_collected=0.0,Interest_collected=0.0,Itbc=0.0,Total_fund=0.0,Fol=0.0,Available_fund=0.0");
                                st.execute("DELETE FROM loan_history");
                                st.execute("DELETE FROM saving_record");
                                st.execute("DELETE FROM loan");
                                st.execute("DELETE FROM passive_account");
                                
                                JOptionPane.showMessageDialog(this,"All Data Formatted!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                                
                                
                            }catch(Exception e){
                                 System.out.println("error");
                            } 
                }else{
                    System.out.println("Err1");
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        A_table = new javax.swing.JTable();
        Refresh = new javax.swing.JLabel();
        Refresh1 = new javax.swing.JLabel();
        Refresh2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 710));

        Title.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 0, 0));
        Title.setText("Admin Panel");

        A_table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        A_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "S.No", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        A_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A_tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(A_table);
        if (A_table.getColumnModel().getColumnCount() > 0) {
            A_table.getColumnModel().getColumn(1).setMinWidth(50);
            A_table.getColumnModel().getColumn(1).setPreferredWidth(50);
            A_table.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        Refresh.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefreshMouseExited(evt);
            }
        });

        Refresh1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add1.png"))); // NOI18N
        Refresh1.setText("Add Admin");
        Refresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refresh1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Refresh1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Refresh1MouseExited(evt);
            }
        });

        Refresh2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Refresh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delUser.png"))); // NOI18N
        Refresh2.setText("Delete");
        Refresh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refresh2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Refresh2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Refresh2MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Reset all the settings and format all the data!!!");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar1.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Refresh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Refresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void A_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_tableMouseEntered
             // TODO add your handling code here:
    }//GEN-LAST:event_A_tableMouseEntered

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        HomeFrame.changePanel(new Admin_panel());        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseClicked

    private void RefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseEntered
        Refresh.setOpaque(true);
        Refresh.setBackground(Color.pink);         // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseEntered

    private void RefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseExited
        Refresh.setBackground(Color.white);
        Refresh.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseExited

    private void Refresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseClicked
        HomeFrame.changePanel(new Add_user());        // TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseClicked

    private void Refresh1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseEntered
        Refresh1.setOpaque(true);
        Refresh1.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseEntered

    private void Refresh1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseExited
        Refresh1.setBackground(Color.white);
        Refresh1.setOpaque(false);   // TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseExited

    private void Refresh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh2MouseClicked
        int noofselectedrows= A_table.getSelectedRowCount();
            
            if(noofselectedrows>0){
                int rowno=A_table.getSelectedRow();
                
               // System.out.println(rowno); // kati no ko row select bhayo bhanera dekhauchha
                Object aid=A_table.getValueAt(rowno, 0);//this line gies the id of the table like 1,2,3 
                int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                 String sql="DELETE FROM  security WHERE ID='"+aid+"'";
                 if(confirmdelete==0){
                    dtm.removeRow(rowno);//this removable is remoaved by the model
                    try{
                        //now this step is to delete prmanently in database aswell 
                       Statement st=con.createStatement();
                       st.executeUpdate(sql);
                     }catch(Exception e){
                        System.out.println("query not executed");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this,"Please select a Account!!!", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_Refresh2MouseClicked

    private void Refresh2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh2MouseEntered
        Refresh2.setOpaque(true);
        Refresh2.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_Refresh2MouseEntered

    private void Refresh2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh2MouseExited
        Refresh2.setBackground(Color.white);
        Refresh2.setOpaque(false);  // TODO add your handling code here:
    }//GEN-LAST:event_Refresh2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JPanel connectionPanel;

        // Create the labels and text fields.
        JLabel     passwordLabel = new JLabel("Password:   ", JLabel.LEFT);
        JTextField passwordField = new JPasswordField("");
        JLabel     password_err = new JLabel("", JLabel.LEFT);
        connectionPanel = new JPanel(false);
        connectionPanel.setLayout(new BoxLayout(connectionPanel,BoxLayout.Y_AXIS));

        JPanel namePanel1 = new JPanel(false);
        JPanel namePanel2 = new JPanel(false);
        namePanel1.setLayout(new GridLayout(0, 1));
        namePanel2.setLayout(new GridLayout(0, 1));
        namePanel2.add(passwordLabel);

        JPanel fieldPanel2 = new JPanel(false);

        fieldPanel2.setLayout(new GridLayout(0, 1));

        fieldPanel2.add(passwordField);
        fieldPanel2.add(password_err);

        connectionPanel.add(namePanel1);

        connectionPanel.add(namePanel2);
        connectionPanel.add(fieldPanel2);

        // Connect or quit

        int log=JOptionPane.showOptionDialog(null, connectionPanel,
            ConnectTitle,
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null, ConnectOptionNames,
            ConnectOptionNames[0]);

        if(log==0){
            String studentPassword;
            String password=studentPassword = passwordField.getText();

            //int usertype=Integer.parseInt(type);

            con=DBconnection.makeconnection();
            String encryptedpassword=PasswordEncryption.encryptPassword(password);
            String sql="SELECT * FROM security WHERE 1=1";
            //if(!"".equals(encryptedpassword)){
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);

                    while(rs.next()){
                        // String user=rs.getString(2);
                        String pass=rs.getString(3);
                        //System.out.println(user);
                        System.out.println(encryptedpassword);

                        if(encryptedpassword.equals(pass)){
                            password_err.setText("Successfully Loged in!!!");
                            System.out.println("pp matched");
                            reset();
                            return;
                        }

                    }
                    password_err.setText("Incorrect Password!!!");
                    System.out.println("hahaa comedy vayo");
                    JOptionPane.showMessageDialog(this,"Incorrect Password!!!","Alert",JOptionPane.PLAIN_MESSAGE);

                }catch(Exception e){
                    System.out.println(sql);
                }
                //}else{
                //  new Aprove_req();
                // }

        }else{
            return;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable A_table;
    private javax.swing.JLabel Refresh;
    private javax.swing.JLabel Refresh1;
    private javax.swing.JLabel Refresh2;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
