/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;


import java.awt.Color;

import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import com.lowagie.text.Document;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Akass
 */
public class Display_members extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    String dirName = "E:\\hmc\\";
    String fileName = ".pdf";

    /**
     * Creates new form Display_members
     */
    public Display_members() {
        initComponents();
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM members WHERE 1=1";
        
        dtm=(DefaultTableModel)Display_table.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                     int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getString(9),rs.getString(10)});
                      
                    }
                    

                   
                }
                catch(Exception e){
                    System.out.println("Query not executed ");
                }
                
             
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bkpanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display_table = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        Search_n = new javax.swing.JTextField();
        Add_member = new javax.swing.JLabel();
        Ediit_member = new javax.swing.JLabel();
        Del_member = new javax.swing.JLabel();
        Refresh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Refresh1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 730));

        Bkpanel.setBackground(new java.awt.Color(255, 255, 255));
        Bkpanel.setPreferredSize(new java.awt.Dimension(901, 710));

        Title.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 0, 0));
        Title.setText("Members");

        Display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No", "Account ID", "Name", "Address", "Mobile Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Display_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Display_tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Display_table);
        if (Display_table.getColumnModel().getColumnCount() > 0) {
            Display_table.getColumnModel().getColumn(0).setMinWidth(50);
            Display_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            Display_table.getColumnModel().getColumn(0).setMaxWidth(50);
            Display_table.getColumnModel().getColumn(1).setMinWidth(150);
            Display_table.getColumnModel().getColumn(1).setPreferredWidth(150);
            Display_table.getColumnModel().getColumn(1).setMaxWidth(150);
            Display_table.getColumnModel().getColumn(3).setMinWidth(200);
            Display_table.getColumnModel().getColumn(3).setPreferredWidth(200);
            Display_table.getColumnModel().getColumn(3).setMaxWidth(200);
            Display_table.getColumnModel().getColumn(4).setMinWidth(150);
            Display_table.getColumnModel().getColumn(4).setPreferredWidth(150);
            Display_table.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Add_member.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Add_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add1.png"))); // NOI18N
        Add_member.setText("Add Member");
        Add_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_memberMouseExited(evt);
            }
        });

        Ediit_member.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Ediit_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editdoc.png"))); // NOI18N
        Ediit_member.setText("Edit Members");
        Ediit_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ediit_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ediit_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ediit_memberMouseExited(evt);
            }
        });

        Del_member.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.PNG"))); // NOI18N
        Del_member.setText("Delete member");
        Del_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Del_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Del_memberMouseExited(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefreshMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/showStudents.png"))); // NOI18N
        jLabel7.setText("View details");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar1.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        Refresh1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        Refresh1.setText("Export Data");
        Refresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refresh1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Refresh1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Refresh1MouseExited(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Title1.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout BkpanelLayout = new javax.swing.GroupLayout(Bkpanel);
        Bkpanel.setLayout(BkpanelLayout);
        BkpanelLayout.setHorizontalGroup(
            BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BkpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                    .addGroup(BkpanelLayout.createSequentialGroup()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BkpanelLayout.createSequentialGroup()
                                .addComponent(Search_n, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search))
                            .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Ediit_member, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Del_member, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add_member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refresh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, Short.MAX_VALUE)
        );
        BkpanelLayout.setVerticalGroup(
            BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BkpanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_n, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BkpanelLayout.createSequentialGroup()
                        .addComponent(Add_member, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ediit_member, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Del_member, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(Bkpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   
    
    
    private void Del_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseClicked

            //using mouse to delete the data permanently
          
        int noofselectedrows= Display_table.getSelectedRowCount();
            
            if(noofselectedrows>0){
                int rowno=Display_table.getSelectedRow();
                
               // System.out.println(rowno); // kati no ko row select bhayo bhanera dekhauchha
                Object aid=Display_table.getValueAt(rowno, 1);//this line gies the id of the table like 1,2,3 
                int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                //System.out.println(confirmdelete);
             //   System.out.println(cid);
                String sql="DELETE FROM members WHERE AID='"+aid+"'";
                String sql2="DELETE FROM account WHERE AID='"+aid+"'";
                String sql3="DELETE FROM saving_record WHERE AID='"+aid+"'";
                String sql4="DELETE FROM passive_account WHERE AID='"+aid+"'";
                if(confirmdelete==0){
                    dtm.removeRow(rowno);//this removable is remoaved by the model
                    try{
                        //now this step is to delete prmanently in database aswell 
                       Statement st=con.createStatement();
                       st.executeUpdate(sql);
                       st.executeUpdate(sql2);
                       st.executeUpdate(sql3);
                       st.executeUpdate(sql4);
                    }catch(Exception e){
                        System.out.println("query not executed");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this,"Please select a Account!!!", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
        

// TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseClicked

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked

        HomeFrame.changePanel(new Display_members());


// TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
         //Filtering code
        String name=Search_n.getText();
        String sql="SELECT * FROM members WHERE 1=1"; //this selects all the rows
               if(!"".equals(name)){
            sql+=" AND Name LIKE '"+name+"%'"; //if blank will not return anything
            //displaying filtered names
        con=DBconnection.makeconnection();
            dtm=(DefaultTableModel)Display_table.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                    int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getString(10)});
                      
                    }
                }
                catch(Exception e){
                    System.out.println("Query not executed");
                }
      
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void Ediit_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ediit_memberMouseClicked
        
        //selecting the row no of data table and passing to constructor in edit panel
        
        boolean isrowselected=Display_table.getSelectedRowCount()>0;
        
        if(isrowselected==true){
            int rowno=Display_table.getSelectedRow();
            Object member_id=Display_table.getValueAt(rowno,1);
            HomeFrame.changePanel(new Edit_members(member_id));
            
        }else{
            JOptionPane.showMessageDialog(this,"Please select Account!!!","Alert",JOptionPane.PLAIN_MESSAGE);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_Ediit_memberMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        boolean isrowselected=Display_table.getSelectedRowCount()>0;

        if(isrowselected==true){
            int rowno=Display_table.getSelectedRow();
            Object aid=Display_table.getValueAt(rowno,1);
            HomeFrame.changePanel(new Display_person(aid));
            //System.out.println(students_id);

        }else{
            JOptionPane.showMessageDialog(this,"Please select Account!!!","Alert",JOptionPane.PLAIN_MESSAGE);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Add_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_memberMouseClicked
                HomeFrame.changePanel(new Add_Member());        // TODO add your handling code here:
    }//GEN-LAST:event_Add_memberMouseClicked

    private void Add_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_memberMouseEntered
        Add_member.setOpaque(true);
        Add_member.setBackground(Color.pink);        // TODO add your handling code here:
    }//GEN-LAST:event_Add_memberMouseEntered

    private void Add_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_memberMouseExited
        Add_member.setBackground(Color.white);
        Add_member.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_Add_memberMouseExited

    private void Ediit_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ediit_memberMouseEntered
        Ediit_member.setOpaque(true);
        Ediit_member.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_Ediit_memberMouseEntered

    private void Ediit_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ediit_memberMouseExited
        Ediit_member.setBackground(Color.white);
        Ediit_member.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_Ediit_memberMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setOpaque(true);
        jLabel7.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setBackground(Color.white);
        jLabel7.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void Del_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseEntered
        Del_member.setOpaque(true);
        Del_member.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseEntered

    private void Del_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseExited
        Del_member.setBackground(Color.white);
        Del_member.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseExited

    private void RefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseEntered
        Refresh.setOpaque(true);
        Refresh.setBackground(Color.pink);// TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseEntered

    private void RefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseExited
        Refresh.setBackground(Color.white);
        Refresh.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseExited

    private void Refresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(dirName));
        chooser.setSelectedFile(new File(fileName));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int code = chooser.showSaveDialog(Display_table);
            if (code == JFileChooser.APPROVE_OPTION) {
               File selectedFile = chooser.getSelectedFile();
               fileName = selectedFile.getName();
               try{
                        
                        Document doc = new Document(PageSize.A4.rotate(),-60, -60, 72, 72);
                        PdfWriter.getInstance(doc, new FileOutputStream(selectedFile));
                        doc.open();
                        PdfPTable pdfTable = new PdfPTable(Display_table.getColumnCount());
            //adding table headers
                        for (int i = 0; i < Display_table.getColumnCount(); i++) {
                            pdfTable.addCell(Display_table.getColumnName(i));
                        }
            //extracting data from the JTable and inserting it to PdfPTable
                        for (int rows = 0; rows < Display_table.getRowCount() ; rows++) {
                                for (int cols = 0; cols < Display_table.getColumnCount(); cols++) {
                                    pdfTable.addCell(Display_table.getModel().getValueAt(rows, cols).toString());

                                }
                            }
                        doc.add(pdfTable);
                        doc.close();
                        Title1.setText("Data saved successfully !!!");
                    
               }catch(Exception e){
                   System.out.println("err");
               }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseClicked

    private void Refresh1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseEntered

    private void Refresh1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Refresh1MouseExited

    private void Display_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display_tableMouseEntered
        Title1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Display_tableMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_member;
    private javax.swing.JPanel Bkpanel;
    private javax.swing.JLabel Del_member;
    private javax.swing.JTable Display_table;
    private javax.swing.JLabel Ediit_member;
    private javax.swing.JLabel Refresh;
    private javax.swing.JLabel Refresh1;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Search_n;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
