/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Akass
 */
public class Edit_members extends javax.swing.JPanel {
    //displaying the previous data from database to edit
        String aid=null;
        Connection con=null;
        // receives the object memberid by this constructor from display table edit buttom and display the  datas
        public Edit_members(Object memberid){     
        initComponents();
        
        con=DBconnection.makeconnection();
        String sql="SELECT * From members WHERE 1=1 AND Aid='"+memberid+"'"; //the first one is selected
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            rs.next();
            this.aid=rs.getString(2);
            ID_n.setText(rs.getString(2));
            Name_n.setText(rs.getString(3));
          //  Gender.setActionCommand(rs.getString(5));
            Citizenship_n.setText(rs.getString(5));
            Ctzn_n.setText(rs.getString(6));
            Membership_n.setSelectedItem(rs.getString(7));
            
            Permanent_n.setText(rs.getString(8));
            Temporary_n.setText(rs.getString(9));
            Mobile_n.setText(rs.getString(10));
            Home_n.setText(rs.getString(11));
            Email_n.setText(rs.getString(12));
            Father_n.setText(rs.getString(13));
            Mother_n.setText(rs.getString(14));
            Gfather_n.setText(rs.getString(15));
            /*
            //accessing image
            byte[] img = rs.getBytes(16);
             //Resize The ImageIcon
            ImageIcon image = new ImageIcon(img);
            Image im = image.getImage();
            Image myImg = im.getScaledInstance(135,145,Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(myImg);
            Dp.setIcon(newImage);*/
             
            
      
            
            
        }catch(Exception e){
            System.out.println("Query not executed");
        }
        
    }

    /**
     * Creates new form Edit_members
     */
    public Edit_members() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Head = new javax.swing.JLabel();
        Contact_info = new javax.swing.JPanel();
        Address = new javax.swing.JLabel();
        Permanent = new javax.swing.JLabel();
        Permanent_n = new javax.swing.JTextField();
        Temporary = new javax.swing.JLabel();
        Temporary_n = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home_n = new javax.swing.JTextField();
        Mobile = new javax.swing.JLabel();
        Mobile_n = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Email_n = new javax.swing.JTextField();
        Basic_info = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Name_n = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Citizenship = new javax.swing.JLabel();
        Citizenship_n = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        ID_n = new javax.swing.JTextField();
        Membership_type = new javax.swing.JLabel();
        Membership_n = new javax.swing.JComboBox();
        Dp = new javax.swing.JLabel();
        Upload = new javax.swing.JButton();
        Ctzn_no = new javax.swing.JLabel();
        Ctzn_n = new javax.swing.JTextField();
        Other_info = new javax.swing.JPanel();
        Father_n = new javax.swing.JTextField();
        Father = new javax.swing.JLabel();
        Gfather = new javax.swing.JLabel();
        Gfather_n = new javax.swing.JTextField();
        Mother = new javax.swing.JLabel();
        Mother_n = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Counter = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 710));

        Head.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Head.setForeground(new java.awt.Color(153, 0, 0));
        Head.setText("Update the details of member");

        Contact_info.setBackground(new java.awt.Color(204, 204, 255));
        Contact_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Contact_info.setForeground(new java.awt.Color(153, 153, 255));

        Address.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Address.setText("Address");

        Permanent.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Permanent.setText("Permanent");

        Temporary.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Temporary.setText("Temporary");

        Temporary_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Temporary_nActionPerformed(evt);
            }
        });

        Contact.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Contact.setText("Contact");

        Home.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Home.setText("Home number");

        Home_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_nActionPerformed(evt);
            }
        });

        Mobile.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Mobile.setText("Mobile number");

        Email.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Email.setText("Email ID");

        Email_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Contact_infoLayout = new javax.swing.GroupLayout(Contact_info);
        Contact_info.setLayout(Contact_infoLayout);
        Contact_infoLayout.setHorizontalGroup(
            Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_infoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addComponent(Email)
                        .addGap(47, 47, 47)
                        .addComponent(Email_n, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addComponent(Temporary)
                        .addGap(18, 18, 18)
                        .addComponent(Temporary_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home_n, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address)
                            .addComponent(Permanent, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(Permanent_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Contact)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contact_infoLayout.createSequentialGroup()
                                .addComponent(Mobile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mobile_n, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Contact_infoLayout.setVerticalGroup(
            Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contact_infoLayout.createSequentialGroup()
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address)
                            .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mobile_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mobile)))
                    .addGroup(Contact_infoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Permanent)
                            .addComponent(Permanent_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Home)
                        .addComponent(Home_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Temporary)
                        .addComponent(Temporary_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Contact_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(Email_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Basic_info.setBackground(new java.awt.Color(204, 204, 255));
        Basic_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Basic_info.setForeground(new java.awt.Color(153, 153, 255));

        Name.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Name.setText("Name");

        Name_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Name_nKeyTyped(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Gender.setText("Gender");

        Male.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(Male);
        Male.setText("Male");
        Male.setActionCommand("M");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(Female);
        Female.setText("Female");
        Female.setActionCommand("F");

        Citizenship.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Citizenship.setText("Citizenship");

        Citizenship_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citizenship_nActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ID.setText("ID");

        ID_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_nActionPerformed(evt);
            }
        });

        Membership_type.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Membership_type.setText("Membership Type");

        Membership_n.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "General", "Founder", "Executive" }));
        Membership_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Membership_nActionPerformed(evt);
            }
        });

        Dp.setBackground(new java.awt.Color(255, 255, 255));
        Dp.setForeground(new java.awt.Color(255, 255, 255));
        Dp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man.jpg"))); // NOI18N
        Dp.setPreferredSize(new java.awt.Dimension(200, 120));

        Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginpng.png"))); // NOI18N
        Upload.setText("Upload");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        Ctzn_no.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Ctzn_no.setText("Ctzn no.");

        Ctzn_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ctzn_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Basic_infoLayout = new javax.swing.GroupLayout(Basic_info);
        Basic_info.setLayout(Basic_infoLayout);
        Basic_infoLayout.setHorizontalGroup(
            Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basic_infoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Basic_infoLayout.createSequentialGroup()
                            .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Name))
                            .addGap(31, 31, 31))
                        .addGroup(Basic_infoLayout.createSequentialGroup()
                            .addComponent(Membership_type)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addComponent(Gender)
                        .addGap(70, 70, 70)))
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Citizenship_n, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name_n, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Membership_n, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ctzn_no)
                            .addComponent(ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ctzn_n, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_n, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addComponent(Male)
                        .addGap(53, 53, 53)
                        .addComponent(Female)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Basic_infoLayout.setVerticalGroup(
            Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basic_infoLayout.createSequentialGroup()
                .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(Name_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Citizenship)
                            .addComponent(Citizenship_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ctzn_no)
                            .addComponent(Ctzn_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(ID_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Membership_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Membership_type, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender)
                            .addComponent(Male)
                            .addComponent(Female)))
                    .addGroup(Basic_infoLayout.createSequentialGroup()
                        .addComponent(Dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upload)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Other_info.setBackground(new java.awt.Color(204, 204, 255));
        Other_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        Other_info.setForeground(new java.awt.Color(153, 153, 255));

        Father_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Father_nActionPerformed(evt);
            }
        });

        Father.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Father.setText("Father's name");

        Gfather.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Gfather.setText("Grandfather's name");

        Gfather_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gfather_nActionPerformed(evt);
            }
        });

        Mother.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Mother.setText("Mother's name");

        Mother_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mother_nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Other_infoLayout = new javax.swing.GroupLayout(Other_info);
        Other_info.setLayout(Other_infoLayout);
        Other_infoLayout.setHorizontalGroup(
            Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Other_infoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mother_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Other_infoLayout.createSequentialGroup()
                        .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gfather)
                            .addGroup(Other_infoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mother)
                                    .addComponent(Father))))
                        .addGap(10, 10, 10)
                        .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gfather_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Father_n, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Other_infoLayout.setVerticalGroup(
            Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Other_infoLayout.createSequentialGroup()
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Father)
                    .addComponent(Father_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mother_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mother))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Other_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gfather)
                    .addComponent(Gfather_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Grant.png"))); // NOI18N
        Submit.setText("Submit");
        buttonGroup2.add(Submit);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        Cancel.setText("Cancel");
        buttonGroup2.add(Cancel);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Counter.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        Counter.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Submit)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Other_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contact_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Head)
                            .addGap(55, 55, 55)
                            .addComponent(Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Basic_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Basic_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contact_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Other_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Temporary_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Temporary_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Temporary_nActionPerformed

    private void Home_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_nActionPerformed

    private void Email_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_nActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void Citizenship_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citizenship_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citizenship_nActionPerformed

    private void ID_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_nActionPerformed

    private void Ctzn_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ctzn_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ctzn_nActionPerformed

    private void Father_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Father_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Father_nActionPerformed

    private void Gfather_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gfather_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gfather_nActionPerformed

    private void Mother_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mother_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mother_nActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed

        //Upload picture in account form

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            Dp.setIcon(ResizeImage(path));
            //profilepic=path;
              int i=1;
              try{
                    BufferedImage image = ImageIO.read(selectedFile);
                    System.out.println(selectedFile);
                    ImageIO.write(image,"jpg",new File("E:\\hm.jpg"));
                    i++;
              }catch(IOException f){
                  System.out.println("fail");
              }
        }
        //if the user click on save in Jfilechooser
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
             jPanel1.add( new Add_Member());
            
        }
        setLayout(null);
        // setDefaultCloseOperation(jPanel1.EXIT_ON_CLOSE);
        //setLocationRelativeTo(null);
        setSize(200,120);
        setVisible(true);

    }//GEN-LAST:event_UploadActionPerformed

     public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        java.awt.Image img = MyImage.getImage();
        java.awt.Image newImg = img.getScaledInstance(Dp.getWidth(), Dp.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        String name=Name_n.getText();
         String gender=buttonGroup1.getSelection().getActionCommand();
        //String dob=Year.getSelectedItem().toString()+"-"+Month.getSelectedItem().toString()+"-"+Day.getSelectedItem().toString();
        String citizenship=Citizenship_n.getText();
        String ctzn=Ctzn_n.getText();
        String membership=Membership_n.getSelectedItem().toString();
        String cid=ID_n.getText();
        String permanent_a=Permanent_n.getText();
        String temporary_a=Temporary_n.getText();
           
        String mobile_n=Mobile_n.getText();
        String home_n=Home_n.getText();
        String email=Email_n.getText();
        String father=Father_n.getText();
        String mother=Mother_n.getText();
        String gfather=Gfather_n.getText();
        String account="0";
        String Image="E:/hm.jpg";
           //System.out.println(title+price+duration);
           String sql="UPDATE members SET Aid='"+cid+"',Name='"+name+"',Gender='"+gender+"',Citizenship='"+citizenship+"',Ctzn_no='"+ctzn+"' ,Membership_type='"+membership+"',Permanent_address='"+permanent_a+"',Temporary_address='"+temporary_a+"',Mobile_no='"+mobile_n+"' ,Home_no='"+home_n+"',Email='"+email+"',Father='"+father+"' ,Mother='"+mother+"',Grandfather='"+gfather+"',Photo=LOAD_FILE('"+Image+"')  WHERE Aid='"+this.aid+"'";
           String sql2="UPDATE account SET Aid='"+cid+"',Name='"+name+"' WHERE Aid='"+this.aid+"'";
           String sql3="UPDATE saving_record SET Aid='"+cid+"',Name='"+name+"' WHERE Aid='"+this.aid+"'";
           
           System.out.println(sql3);
           try {
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            st.executeUpdate(sql3);
           
            st.executeUpdate(sql2);
              Counter.setText("Record Edited!!!");
        } catch (Exception e) {
           System.out.println("Query Not executed");
        }
         HomeFrame.changePanel(new Display_members());
       
       
        
        
             // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        HomeFrame.changePanel(new Display_members());
      //  HomeFrame.changePanel(new HomeFrame());
        
// TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void Name_nKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Name_nKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_Name_nKeyTyped

    private void Membership_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Membership_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Membership_nActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JPanel Basic_info;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Citizenship;
    private javax.swing.JTextField Citizenship_n;
    private javax.swing.JLabel Contact;
    private javax.swing.JPanel Contact_info;
    private javax.swing.JLabel Counter;
    private javax.swing.JTextField Ctzn_n;
    private javax.swing.JLabel Ctzn_no;
    private javax.swing.JLabel Dp;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Email_n;
    private javax.swing.JLabel Father;
    private javax.swing.JTextField Father_n;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gfather;
    private javax.swing.JTextField Gfather_n;
    private javax.swing.JLabel Head;
    private javax.swing.JLabel Home;
    private javax.swing.JTextField Home_n;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField ID_n;
    private javax.swing.JRadioButton Male;
    private javax.swing.JComboBox Membership_n;
    private javax.swing.JLabel Membership_type;
    private javax.swing.JLabel Mobile;
    private javax.swing.JTextField Mobile_n;
    private javax.swing.JLabel Mother;
    private javax.swing.JTextField Mother_n;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Name_n;
    private javax.swing.JPanel Other_info;
    private javax.swing.JLabel Permanent;
    private javax.swing.JTextField Permanent_n;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Temporary;
    private javax.swing.JTextField Temporary_n;
    private javax.swing.JButton Upload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
