/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akass
 */
public class Issue_loan extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    Double available_fund=0.0;
    /**
     * Creates new form Issue_loan
     */
    public Issue_loan() {
        initComponents();
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM account WHERE Status='Active'";
        
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                     int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getDouble(4)});
                      
                    }
                    ResultSet rs1=st.executeQuery("SELECT * FROM capital WHERE Name='Capital'");
                    while(rs1.next()){
                            this.available_fund=rs1.getDouble(8);
                    }
                    System.out.println(available_fund);

                   
                }
                catch(Exception e){
                    System.out.println("Query not executed ");
                }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Account_id = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Month = new javax.swing.JComboBox();
        Year = new javax.swing.JComboBox();
        Day = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Rate = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Interest = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Total_amount = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        End_date = new javax.swing.JTextField();
        err1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Del_member1 = new javax.swing.JLabel();
        Msg = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 710));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "S.No", "Account ID", "Name", "Savings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Account ID");

        Account_id.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N

        Name.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N

        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Baishak", "Jestha", "Ashad", "Shrawan", "Bhadra", "Aswin", "Kartik", "Mangsir", "Poush", "Magh", "Falgun", "Chaitra" }));

        Year.setEditable(true);
        Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        Day.setEditable(true);
        Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("End Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Issue Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Amount");

        Amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rate");

        Rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RateKeyTyped(evt);
            }
        });

        Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TimeKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Time");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calc.png"))); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Interest");

        Interest.setEditable(false);
        Interest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Total Amount");

        Total_amount.setEditable(false);
        Total_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bookIssue.png"))); // NOI18N
        jButton3.setText("Issue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        End_date.setEditable(false);
        End_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        err1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        err1.setForeground(new java.awt.Color(204, 0, 0));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Del_member1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        Del_member1.setText("Refresh");
        Del_member1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_member1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Del_member1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Account_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(47, 47, 47)
                                .addComponent(Day, 0, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(25, 25, 25)
                                .addComponent(Total_amount)
                                .addGap(55, 55, 55))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Amount)
                                            .addComponent(Rate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(51, 51, 51))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(61, 61, 61)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(End_date)
                                            .addComponent(Interest))))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(98, 98, 98))
                                    .addComponent(err1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Del_member1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Account_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(err1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(End_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addGap(30, 30, 30))
        );

        Msg.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        Msg.setForeground(new java.awt.Color(204, 0, 0));

        Title.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 0, 0));
        Title.setText("Loan form");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Title)
                        .addComponent(jButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addGap(393, 393, 393))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        boolean isrowselected=jTable1.getSelectedRowCount()>0;
        
        if(isrowselected==true){
            int rowno=jTable1.getSelectedRow();
            Object member_id=jTable1.getValueAt(rowno,1);
            con=DBconnection.makeconnection();
            String sql="SELECT * FROM members WHERE Aid='"+member_id+"'";
             try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                    while(rs.next()){
                        Account_id.setText(rs.getString(2));
                        Name.setText(rs.getString(3));
                        System.out.println("success");
                    }
                }
                catch(Exception e){
                    System.out.println("Query not executed ");
                }
            
            
            
            
        }else{
            JOptionPane.showMessageDialog(this,"Please select the row","Alert",JOptionPane.PLAIN_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        
        boolean isrowselected=jTable1.getSelectedRowCount()>0;        
        if(isrowselected==true){
        String d1=Day.getSelectedItem().toString();
        if(d1=="-" ){
                    JOptionPane.showMessageDialog(this," Day cannot be Empty!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                    return;
            }
        String d2=Month.getSelectedItem().toString();
        if(d2=="-" ){
                    JOptionPane.showMessageDialog(this," Month cannot be Empty!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                    return;
            }
        String d3=Year.getSelectedItem().toString();
        if(d3=="-" ){
                    JOptionPane.showMessageDialog(this," Year cannot be Empty!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                    return;
            }
            
            String P=Amount.getText();
            if(Validate.checklength(P)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Amount annot be empty!!!");
                    Amount.requestFocus();
                    return;
            }
            String R=Rate.getText();
            if(Validate.checklength(R)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Rate cannot be empty!!!");
                    Rate.requestFocus();
                    return;
            }
            String T=Time.getText();
            if(Validate.checklength(T)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Time cannot be empty!!!");
                    Time.requestFocus();
                    return;
            }
            
            String month=Month.getSelectedItem().toString();
           // Double month=Double.parseDouble(mon.toString());          
            String d=Day.getSelectedItem().toString();
            Double day=Double.parseDouble(d.toString());
            
            String y=Year.getSelectedItem().toString();
            Double year=Double.parseDouble(y.toString());
            
            
            int m = 0; 
            if("Baishak".equals(month)){
                m=1;
            }else if("Jestha".equals(month)){
                m=2;
            }else if("Ashad".equals(month)){
                m=3;
            }else if("Shrawan".equals(month)){
                m=4;
            }else if("Bhadra".equals(month)){
                m=5;
            }else if("Aswin".equals(month)){
                m=6;
            }else if("Kartik".equals(month)){
                m=7;
            }else if("Mangsir".equals(month)){
                m=8;
            }else if("Poush".equals(month)){
                m=9;
            }else if("Magh".equals(month)){
                m=10;
            }else if("Falgun".equals(month)){
                m=11;
            }else if("Chaitra".equals(month)){
                m=12;
            }
       
            Double amount=Double.parseDouble(Amount.getText().toString());            
            Double rate=Double.parseDouble(Rate.getText().toString());
            Double time=Double.parseDouble(Time.getText().toString());
            ///calculation of time
            int new_day=(int)(day+0);
            int new_month=(int)(new_day/30);
            new_day=(new_day%30)+1;
            new_month=(int) (new_month+m+time);
            int new_year=(int) (new_month/12);
            new_month=new_month%12;
            new_year=(int)(new_year+year);
            if(new_month==0){
                new_month=12;
                new_year=(int)(year+0);
            }
            String Month=null;
            if(new_month==1){
                Month="Baishak";
            }else if(new_month==2){
                Month="Jestha";
            }else if(new_month==3){
                Month="Ashad";
            }else if(new_month==4){
                Month="Shrawan";
            }else if(new_month==5){
                Month="Bhadra";
            }else if(new_month==6){
                Month="Aswin";
            }else if(new_month==7){
                Month="Kartik";
            }else if(new_month==8){
                Month="Mangsir";
            }else if(new_month==9){
                Month="Poush";
            }else if(new_month==10){
                Month="Magh";
            }else if(new_month==11){
                Month="Falgun";
            }else if(new_month==12){
                Month="Chaitra";
            }
            End_date.setText(new_day+" - "+Month+" - "+new_year);
            
            //calculation of interest
           // float Time=(float)(time/12);
            Double interest=((amount*rate*time)/100);
            Interest.setText(new DecimalFormat(".###").format(interest));
            
            Double total_amount=amount+interest;
            Total_amount.setText(new DecimalFormat(".###").format(total_amount));
                    
            
            
            //System.out.println(new_day+"-"+new_month+"-"+new_year); 
            //System.out.println(interest);
            //System.out.println(day*m*year);
            
           
            
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Account!!!","Alert",JOptionPane.PLAIN_MESSAGE);
        }
        
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyTyped
                err1.setText("");
               

            // TODO add your handling code here:
    }//GEN-LAST:event_AmountKeyTyped

    private void RateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RateKeyTyped
         err1.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_RateKeyTyped

    private void TimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TimeKeyTyped
             err1.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_TimeKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    boolean isrowselected=jTable1.getSelectedRowCount()>0;        
        if(isrowselected==true){
           
              String P=Amount.getText();
            if(Validate.checklength(P)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Amount cannot be empty!!!");
                    Amount.requestFocus();
                    return;
            }
            String R=Rate.getText();
            if(Validate.checklength(R)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Rate cannot be empty!!!");
                    Rate.requestFocus();
                    return;
            }
            String T=Time.getText();
            if(Validate.checklength(T)==false){
                    //JOptionPane.showMessageDialog(this,"Please provide first name","Alert",JOptionPane.PLAIN_MESSAGE);
                    err1.setText("Time cannot be empty!!!");
                    Time.requestFocus();
                    return;
            }
                
        String name=Name.getText();
        String id=Account_id.getText();
        String date1=Year.getSelectedItem().toString()+"-"+Month.getSelectedItem().toString()+"-"+Day.getSelectedItem().toString();
        String amount=Amount.getText();
        String rate=Rate.getText();
        String duration=Time.getText();
        String interest=Interest.getText();
        String date2=End_date.getText();
        String total=Total_amount.getText();
        String payment="Due";
        
        con=DBconnection.makeconnection();  
            //inserting into loan and loan history.
        String sql="INSERT INTO loan (Aid, Name, Loan_taken_date, Loan_amount,Rate,Duration, Interest, Total_amount, End_date, Payment) VALUES ('"+id+"','"+name+"','"+date1+"','"+amount+"','"+rate+"','"+duration+"','"+interest+"','"+total+"','"+date2+"','"+payment+"')";//INSERT INTO new(Image) VALUES(LOAD_FILE('D:/Image/a.jpg'));
        String sql2="INSERT INTO loan_history (Aid, Name, Loan_taken_date, Loan_amount,Rate,Duration, Interest, Total_amount, End_date, Payment) VALUES ('"+id+"','"+name+"','"+date1+"','"+amount+"','"+rate+"','"+duration+"','"+interest+"','"+total+"','"+date2+"','"+payment+"')";//INSERT INTO new(Image) VALUES(LOAD_FILE('D:/Image/a.jpg'));
        
        try{
             Statement st=con.createStatement(); 
            st.execute(sql);
            st.execute(sql2);
            //updating the capital table
            st.execute("UPDATE capital SET Fol=Fol+"+amount+" WHERE Name='Capital'");
            st.execute("UPDATE capital SET Itbc=Itbc+"+interest+" WHERE Name='Capital'");
            JOptionPane.showMessageDialog(this,"Loan issued successfully!!!\n Your last payment date is "+date2+"","Alert",JOptionPane.PLAIN_MESSAGE);
        
              
            Msg.setText("Loan issued successfully !!!");
            Name.setText("");
            Account_id.setText("");
            Amount.setText("");
            Rate.setText("");
            Time.setText("");
            Interest.setText("");
            End_date.setText("");
            Total_amount.setText("");
            Year.setSelectedItem("-");
            Month.setSelectedItem("-");
            Day.setSelectedItem("-");
        }catch(Exception e){
            System.out.println(sql);
             //Msg.setText("Loan already taken !!!");
           JOptionPane.showMessageDialog(this,"Loan already taken.\n Please pay your dues first!!!","Alert",JOptionPane.PLAIN_MESSAGE);
      
        } 
        
        
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Account !!!","Alert",JOptionPane.PLAIN_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        Msg.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            Msg.setText("Loan Canceled!!!");
            Name.setText("");
            Account_id.setText("");
            Amount.setText("");
            Rate.setText("");
            Time.setText("");
            Interest.setText("");
            End_date.setText("");
            Total_amount.setText("");
            Year.setSelectedItem("-");
            Month.setSelectedItem("-");
            Day.setSelectedItem("-");     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             //Filtering code
        String name=jTextField1.getText();
        String sql="SELECT * FROM account WHERE 1=1"; //this selects all the rows
        if(!"".equals(name)){
            sql+=" AND Name LIKE '"+name+"%'"; //if blank will not return anything
            //displaying filtered names
            con=DBconnection.makeconnection();
            dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0); //its removes the blank table and set rows to zero.

            try{
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                int i=1;
                while(rs.next()){
                    dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getString(4)});
                      
                }
            }
            catch(Exception e){
                System.out.println("Query not executed");
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
}
    private void AmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyReleased
             
        //warning when balance is insufficent to lend loan
        Double amount=Double.parseDouble(Amount.getText().toString());            
                if(amount>=available_fund){
                    JOptionPane.showMessageDialog(this,"You don't have sufficent available balance for loan, Please Recheck!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                    Amount.setText("");
                } // TODO add your handling code here:
    }//GEN-LAST:event_AmountKeyReleased

    private void Del_member1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member1MouseClicked
        HomeFrame.changePanel(new Issue_loan());        // TODO add your handling code here:
    }//GEN-LAST:event_Del_member1MouseClicked
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_id;
    private javax.swing.JTextField Amount;
    private javax.swing.JComboBox Day;
    private javax.swing.JLabel Del_member1;
    private javax.swing.JTextField End_date;
    private javax.swing.JTextField Interest;
    private javax.swing.JComboBox Month;
    private javax.swing.JLabel Msg;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Rate;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Total_amount;
    private javax.swing.JComboBox Year;
    private javax.swing.JLabel err1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
