/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import com.lowagie.text.Document;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akass
 */
public class Loan_history extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    
      String dirName = "E:\\hmc\\";
      String fileName = ".pdf";
    /**
     * Creates new form Loan_history
     */
    public Loan_history() {
        initComponents();
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM loan_history WHERE 1=1";
        
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                     int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
                      
                    }
                    

                   
                }
                catch(Exception e){
                    System.out.println("Query not executed ");
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        Search_n = new javax.swing.JTextField();
        Del_member = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Del_member1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 710));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Account ID", "Name", "Issue Date", "Loan Amount", "Rate", "Duration", "Interest", "Tota Amount", "Date for Payment", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(1).setMinWidth(80);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(2).setMinWidth(140);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(140);
            jTable1.getColumnModel().getColumn(5).setMinWidth(40);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(6).setMinWidth(55);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(10).setMinWidth(60);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(60);
        }

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Del_member.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.PNG"))); // NOI18N
        Del_member.setText("Clear history");
        Del_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Del_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Del_memberMouseExited(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 0, 0));
        Title.setText("Loan History ");

        Del_member1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bookIssue.png"))); // NOI18N
        Del_member1.setText("Export");
        Del_member1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_member1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Del_member1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Del_member1MouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar1.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        Title1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Title1.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_n, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Del_member1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Del_member, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_n, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Del_member, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Del_member1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        //Filtering code
        String name=Search_n.getText();
        String sql="SELECT * FROM loan_history WHERE 1=1"; //this selects all the rows
        if(!"".equals(name)){
            sql+=" AND Name LIKE '"+name+"%'"; //if blank will not return anything
            //displaying filtered names
            con=DBconnection.makeconnection();
            dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0); //its removes the blank table and set rows to zero.

            try{
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                int i=1;
                while(rs.next()){
                    dtm.addRow(new Object[]{i++,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});

                }
            }
            catch(Exception e){
                System.out.println("Query not executed");
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void Del_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseClicked

       
            int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete all?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmdelete==0){
                try{
                    //now this step is to delete prmanently in database aswell
                    Statement st=con.createStatement();
                    st.executeUpdate( "DELETE FROM loan_history" );
                    HomeFrame.changePanel(new Loan_history());
                    Title1.setText("Loan history cleared");
                }catch(Exception e){
                    System.out.println("query not executed");
                }
            }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
            Title1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void Del_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseEntered
        Del_member.setOpaque(true);
        Del_member.setBackground(Color.pink);        // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseEntered

    private void Del_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_memberMouseExited
        Del_member.setBackground(Color.white);
        Del_member.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_Del_memberMouseExited

    private void Del_member1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member1MouseClicked
        
      JFileChooser chooser = new JFileChooser();
      chooser.setCurrentDirectory(new File(dirName));
      chooser.setSelectedFile(new File(fileName));
      chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int code = chooser.showSaveDialog(jTable1);
            if (code == JFileChooser.APPROVE_OPTION) {
               File selectedFile = chooser.getSelectedFile();
               fileName = selectedFile.getName();
               try{
                        
                        Document doc = new Document(PageSize.A4.rotate(),-60, -60, 72, 72);
                        PdfWriter.getInstance(doc, new FileOutputStream(selectedFile));
                        doc.open();
                        PdfPTable pdfTable = new PdfPTable(jTable1.getColumnCount());
            //adding table headers
                        for (int i = 0; i < jTable1.getColumnCount(); i++) {
                            pdfTable.addCell(jTable1.getColumnName(i));
                        }
            //extracting data from the JTable and inserting it to PdfPTable
                        for (int rows = 0; rows < jTable1.getRowCount() ; rows++) {
                                for (int cols = 0; cols < jTable1.getColumnCount(); cols++) {
                                    pdfTable.addCell(jTable1.getModel().getValueAt(rows, cols).toString());

                                }
                            }
                        doc.add(pdfTable);
                        doc.close();
                        Title1.setText("Data saved successfully !");
                    
               }catch(Exception e){
                   System.out.println("err");
               }
            }
        
        
            // TODO add your handling code here:
    }//GEN-LAST:event_Del_member1MouseClicked

    private void Del_member1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member1MouseEntered
                Del_member1.setOpaque(true);
        Del_member1.setBackground(Color.pink);    // TODO add your handling code here:
    }//GEN-LAST:event_Del_member1MouseEntered

    private void Del_member1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member1MouseExited
        Del_member1.setBackground(Color.white);
        Del_member1.setOpaque(false);// TODO add your handling code here:
    }//GEN-LAST:event_Del_member1MouseExited

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        Title1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Del_member;
    private javax.swing.JLabel Del_member1;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Search_n;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
