/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Akass
 */
public class Monthly_saving extends javax.swing.JPanel {
    Connection con=null;
    DefaultTableModel dtm=null;
    
    /**
     * Creates new form Monthly_saving
     */
    public Monthly_saving() {
        initComponents();
        
        con=DBconnection.makeconnection();
        String sql="SELECT * FROM account WHERE 1=1";
        dtm=(DefaultTableModel)Monthly_table.getModel();
        dtm.setRowCount(0); //its removes the blank table and set rows to zero.
                
                try{
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery(sql);
                    int i=1;
                    while(rs.next()){
                        dtm.addRow(new Object[]{rs.getInt(1),i++,rs.getString(2),rs.getString(3)});
                      
                    }
                }
                catch(Exception e){
                    System.out.println("Query not executed ");
                }
                
                 TableColumnModel tcm=Monthly_table.getColumnModel();
                TableColumn tc=tcm.getColumn(0);
                tc.setPreferredWidth(0);
                tc.setMinWidth(0);
                tc.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Monthly_table = new javax.swing.JTable();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Del_member3 = new javax.swing.JLabel();
        Save1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 730));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 710));

        Title.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 0, 0));
        Title.setText("Monthly Saving");

        Monthly_table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Monthly_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,  new Double(0.0)},
                {null, null, null, null,  new Double(0.0)},
                {null, null, null, null,  new Double(0.0)},
                {null, null, null, null,  new Double(0.0)}
            },
            new String [] {
                "ID", "S.No", "Account ID", "Name", "Saving"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Monthly_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Monthly_tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Monthly_table);
        if (Monthly_table.getColumnModel().getColumnCount() > 0) {
            Monthly_table.getColumnModel().getColumn(0).setPreferredWidth(30);
            Monthly_table.getColumnModel().getColumn(1).setMinWidth(50);
            Monthly_table.getColumnModel().getColumn(1).setPreferredWidth(50);
            Monthly_table.getColumnModel().getColumn(1).setMaxWidth(50);
            Monthly_table.getColumnModel().getColumn(2).setMinWidth(150);
            Monthly_table.getColumnModel().getColumn(2).setPreferredWidth(150);
            Monthly_table.getColumnModel().getColumn(2).setMaxWidth(150);
            Monthly_table.getColumnModel().getColumn(4).setMinWidth(150);
            Monthly_table.getColumnModel().getColumn(4).setPreferredWidth(150);
            Monthly_table.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Grant.png"))); // NOI18N
        Save.setText("Diposit");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Baishak", "Jestha", "Ashad", "Shrawan", "Bhadra", "Aswin", "Kartik", "Mangsir", "Poush", "Magh", "Falgun", "Chaitra" }));

        Del_member3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Del_member3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        Del_member3.setText("Refresh");
        Del_member3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_member3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Del_member3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Del_member3MouseExited(evt);
            }
        });

        Save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        Save1.setText("Cancel");
        Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Save1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Save))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(Del_member3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, 98, Short.MAX_VALUE)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(320, 320, 320)))
                        .addGap(283, 283, 283)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Del_member3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Save1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save1ActionPerformed
        HomeFrame.changePanel(new Monthly_saving());        // TODO add your handling code here:
    }//GEN-LAST:event_Save1ActionPerformed

    private void Del_member3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member3MouseExited
        Del_member3.setBackground(Color.white);
        Del_member3.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_Del_member3MouseExited

    private void Del_member3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member3MouseEntered
        Del_member3.setOpaque(true);
        Del_member3.setBackground(Color.pink);         // TODO add your handling code here:
    }//GEN-LAST:event_Del_member3MouseEntered

    private void Del_member3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_member3MouseClicked
        HomeFrame.changePanel(new Monthly_saving());        // TODO add your handling code here:
    }//GEN-LAST:event_Del_member3MouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        //Date nd time
        //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Calendar cal = Calendar.getInstance();
        String date=dateFormat.format(cal.getTime());
        System.out.println(date);

        //getting values from each cell
        TableModel model = Monthly_table.getModel();
        int cols = model.getColumnCount();
        int row = model.getRowCount();
        int i;
        String month=jComboBox1.getSelectedItem().toString();
        con=DBconnection.makeconnection();
        if(month=="-" ){
            JOptionPane.showMessageDialog(this,"Please provide MONTH!!!","Alert",JOptionPane.PLAIN_MESSAGE);
            return;
        }
        System.out.println(row);
        Object[] values = new Object[ row ];
        Object[] id=new Object[row];
        for (i = 0; i <row; i++ ) {
            values[ i ] = model.getValueAt( i, 4 );
            id[i]=model.getValueAt(i,2);
            System.out.print(id[i]);
            System.out.println(" "+values[i]);

            //adding values of cell with existing values of db and restoring each in db
            try {
                Statement st=con.createStatement();
                st.executeUpdate("UPDATE account SET Account=Account+"+values[i]+" WHERE Aid='"+id[i]+"'");
                if(month=="Baishak"){
                    st.executeUpdate("UPDATE saving_record SET Date1='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Jestha"){
                    st.executeUpdate("UPDATE saving_record SET Date2='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Ashad"){
                    st.executeUpdate("UPDATE saving_record SET Date3='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Shrawan"){
                    st.executeUpdate("UPDATE saving_record SET Date4='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Bhadra"){
                    st.executeUpdate("UPDATE saving_record SET Date5='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Aswin"){
                    st.executeUpdate("UPDATE saving_record SET Date6='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Kartik"){
                    st.executeUpdate("UPDATE saving_record SET Date7='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Mangsir"){
                    st.executeUpdate("UPDATE saving_record SET Date8='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Poush"){
                    st.executeUpdate("UPDATE saving_record SET Date9='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Magh"){
                    st.executeUpdate("UPDATE saving_record SET Date10='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Falgun"){
                    st.executeUpdate("UPDATE saving_record SET Date11='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }else if(month=="Chaitra"){
                    st.executeUpdate("UPDATE saving_record SET Date12='"+date+"',"+month+"='"+values[i]+"' WHERE Aid='"+id[i]+"'");
                }
                jLabel1.setText("Amount added successfully!!!");

            } catch (Exception e) {
                System.out.println("Query Not executed");
                jLabel1.setText("Failed to add Amount!!!");
            }
        }

        // Adding the total sum of monthly collection in capital Table
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT SUM( Account ) FROM account");
            Double sum =0.0;
            while(rs.next()){
                int value=rs.getInt(1);
                sum=sum+value;
            }
            st.execute("UPDATE capital SET Monthly_collected="+sum+" WHERE Name='Capital'");

        }catch(Exception e){
            System.out.println("falied");

        }

        int newrecord=JOptionPane.showConfirmDialog(this, "Amount Successfully Diposited!!! Do yu want to add more??", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        if(newrecord==0){
            HomeFrame.changePanel(new Monthly_saving());
        }else{
            HomeFrame.changePanel(new Display_saving());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void Monthly_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Monthly_tableMouseEntered
        jLabel1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Monthly_tableMouseEntered
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Del_member3;
    private javax.swing.JTable Monthly_table;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
