/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm.coperation;



import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Akass
 */
public class Reset_all extends javax.swing.JPanel {
    String studentID, studentPassword;
    Connection con=null;
    /**
     * Creates new form Reset
     */
    public Reset_all() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 710));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGap(54, 54, 54)))
        );
    }// </editor-fold>//GEN-END:initComponents
    static String[] ConnectOptionNames = { "Login", "Cancel" };
    static String   ConnectTitle = "User Log in";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       JPanel      connectionPanel;

 	// Create the labels and text fields.
	JLabel     passwordLabel = new JLabel("Password:   ", JLabel.LEFT);
	JTextField passwordField = new JPasswordField("");
        JLabel     password_err = new JLabel("", JLabel.LEFT);
	connectionPanel = new JPanel(false);
	connectionPanel.setLayout(new BoxLayout(connectionPanel,BoxLayout.Y_AXIS));
	
        JPanel namePanel1 = new JPanel(false);
        JPanel namePanel2 = new JPanel(false);
	namePanel1.setLayout(new GridLayout(0, 1));
        namePanel2.setLayout(new GridLayout(0, 1));
        namePanel2.add(passwordLabel);
	
        JPanel fieldPanel2 = new JPanel(false);         
        
	fieldPanel2.setLayout(new GridLayout(0, 1));
       
	fieldPanel2.add(passwordField);
        fieldPanel2.add(password_err);

	
        connectionPanel.add(namePanel1);
	
        connectionPanel.add(namePanel2);
	connectionPanel.add(fieldPanel2);
        
        // Connect or quit
        
	int log=JOptionPane.showOptionDialog(null, connectionPanel, 
                                        ConnectTitle,
                                        JOptionPane.OK_CANCEL_OPTION, 
                                        JOptionPane.INFORMATION_MESSAGE,
                                        null, ConnectOptionNames, 
                                        ConnectOptionNames[0]);  
        
        if(log==0){    
        String password=studentPassword = passwordField.getText();
                  
         //int usertype=Integer.parseInt(type);
        
        con=DBconnection.makeconnection();
        String encryptedpassword=PasswordEncryption.encryptPassword(password);
        String sql="SELECT * FROM security WHERE 1=1";
        //if(!"".equals(encryptedpassword)){
            try{
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                
                while(rs.next()){
                   // String user=rs.getString(2);
                    String pass=rs.getString(3);
                    //System.out.println(user);
                    System.out.println(encryptedpassword);
                    
                        if(encryptedpassword.equals(pass)){
                            password_err.setText("Successfully Loged in!!!");
                            System.out.println("pp matched");  
                            reset();
                            return;
                        } 
                                     
                }
                password_err.setText("Incorrect Password!!!");
                System.out.println("hahaa comedy vayo"); 
                JOptionPane.showMessageDialog(this,"Incorrect Password!!!","Alert",JOptionPane.PLAIN_MESSAGE);
            
            }catch(Exception e){
                System.out.println(sql);
            }
         //}else{
           //  new Aprove_req();
        // }
        
    }else{
        return;
    }
        
     
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void reset()
    {
        System.out.println("success");
        
        con=DBconnection.makeconnection();
        int confirmdelete=JOptionPane.showConfirmDialog(this, "Are you sure you want to erase all the data permanently?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                //System.out.println(confirmdelete);
             //   System.out.println(cid);
                if(confirmdelete==0){
                   
                         try{
                                Statement st=con.createStatement();
                                st.execute("DELETE FROM members");
                                st.execute("DELETE FROM account");
                                st.execute("UPDATE capital SET Monthly_collected=0.0,Interest_collected=0.0,Itbc=0.0,Total_fund=0.0,Fol=0.0,Available_fund=0.0");
                                st.execute("DELETE FROM loan_history");
                                st.execute("DELETE FROM saving_record");
                                st.execute("DELETE FROM loan");
                                st.execute("DELETE FROM passive_account");
                                
                                JOptionPane.showMessageDialog(this,"All Data Formatted!!!","Alert",JOptionPane.PLAIN_MESSAGE);
                                
                                
                            }catch(Exception e){
                                 System.out.println("error");
                            } 
                }else{
                    System.out.println("Err1");
                }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
